language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp-cli
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
    secure: Gk6uROq0sBc9WDPvYl3GCXzLDmDVJOUEQ4+StBSAwVYLWsoftY9uYWANsod+q2bttmarmIuuZ/+K6o6s/8/kYsgHMgbRAeEfk+QI+KGCxhA5dKijosWN0WCuuG6l1XIzaxWriWEDOmB8yH+qMeesHKrH2YPa93b+lRYkLAx/PZM=
