language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp-cli
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

env:
- secure: "QyRFmS/l4hNwPZ6kSwsIYbFa5JqkJ0+nzfmBwZ52pXX7fIkDJUdqn7ixLlsxlwUPCTe51z50lbK/Y3iEkF0OkdUSCb1Kti/TvQYBBg5fYFEQC6qehJEXxgSDRM2adC94mTDyH4xI2s37C7lDZMBfoP8quk/774mtOjwDXe62YL0="
