language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp-cli
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

env:
- secure: "ee7P94FZOaGc4GGufssUxoDcQL/UqJSBjle+Sspwskqn4n3d7J6h39jcgZYV8Riw4876hG24NoHVX9BORaV6SKICYQ9OrmGFQQqmMSNqz+aKoM1zcN/7Fti8w3k9vKcYq8ORAHe7+Wdn13CxptMxKmUVWgLytALMjnj2cakfPoE="
